Various patches (#3)
* Fix build with Qt 5.11_beta3 (dropping qt5_use_modules)

* Add missing header

Resolves the following build-time warning:

[..]/libqmenumodel/src/gtk/gtksimpleactionobserver.c: In function ‘gtk_simple_action_observer_register_action’:
[..]/libqmenumodel/src/gtk/gtksimpleactionobserver.c:147:7: warning: implicit declaration of function ‘gtk_action_observable_register_observer’ [-Wimplicit-function-declaration]
  147 |       gtk_action_observable_register_observer (self->observable, self->action_name, GTK_ACTION_OBSERVER (self));
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[..]/libqmenumodel/src/gtk/gtksimpleactionobserver.c: In function ‘gtk_simple_action_observer_unregister_action’:
[..]/libqmenumodel/src/gtk/gtksimpleactionobserver.c:156:5: warning: implicit declaration of function ‘gtk_action_observable_unregister_observer’ [-Wimplicit-function-declaration]
  156 |     gtk_action_observable_unregister_observer(self->observable, self->action_name, GTK_ACTION_OBSERVER (self));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Remove use of the deprecated QModelIndex::child function

Co-authored-by: Ivan Semkin <ivan@semkin.ru>